version: '2'
services:
  logstash:
    scale: 1
    start_on_create: true
  Vpnc-file-downloader:
    scale: 1
    start_on_create: true
  elasticsearch:
    scale: 1
    start_on_create: true
  Filebeat:
    scale: 1
    start_on_create: true
  kibana:
    scale: 1
    start_on_create: true